//CHMODJOB JOB (ACCT),'CHMOD PERM',
//             CLASS=A,MSGCLASS=H,NOTIFY=&SYSUID
//STEP1  EXEC PGM=BPXBATCH
//STDOUT DD SYSOUT=*
//STDERR DD SYSOUT=*
//SYSIN  DD *
SH chmod 755 /tmp/jira_create_subtask.sh
/*
//
